cache_dir: "data/cache/gefs"   # 0.25 degree GEFSv12 files
data_path: "data/ICs"  # generated ICs 
pred_path: "data/forecast"   # forecast path
lead_time: 384

checkpoint: "../train/outputs/checkpoint/8faf0777-a87d-4764-a0a9-933ef69e69a1/inference-last.ckpt" 

resolution: '0p25'
fjob: "fjob"
save_grib: false

